// <auto-generated />
using System;
using GestionHotelSahaBeach.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionHotelSahaBeach.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221228220117_iinitial")]
    partial class iinitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionHotelSahaBeach.Chambre", b =>
                {
                    b.Property<int>("idchambre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idchambre"));

                    b.Property<int>("NbrePlaces")
                        .HasColumnType("int");

                    b.Property<int>("NumChambre")
                        .HasColumnType("int");

                    b.Property<string>("etat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("prix")
                        .HasColumnType("float");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idchambre");

                    b.ToTable("Chambre");
                });

            modelBuilder.Entity("GestionHotelSahaBeach.Facture", b =>
                {
                    b.Property<int>("idfacture")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idfacture"));

                    b.Property<int?>("clientidclient")
                        .HasColumnType("int");

                    b.Property<DateTime?>("date_facture")
                        .HasColumnType("datetime2");

                    b.Property<int?>("idclient")
                        .HasColumnType("int");

                    b.Property<double>("montant")
                        .HasColumnType("float");

                    b.HasKey("idfacture");

                    b.HasIndex("clientidclient");

                    b.ToTable("Facture");
                });

            modelBuilder.Entity("GestionHotelSahaBeach.Questionresponse", b =>
                {
                    b.Property<int>("idquestion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idquestion"));

                    b.Property<string>("question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("response")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idquestion");

                    b.ToTable("Questionresponse");
                });

            modelBuilder.Entity("GestionHotelSahaBeach.ReservationChambre", b =>
                {
                    b.Property<int>("idreserCh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idreserCh"));

                    b.Property<DateTime?>("Date_arrivee")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_depart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_reser")
                        .HasColumnType("datetime2");

                    b.Property<int>("NombreAdultes")
                        .HasColumnType("int");

                    b.Property<int>("NombreEnfants")
                        .HasColumnType("int");

                    b.Property<int?>("idchambre")
                        .HasColumnType("int");

                    b.Property<int?>("idclient")
                        .HasColumnType("int");

                    b.HasKey("idreserCh");

                    b.ToTable("ReservChambre");
                });

            modelBuilder.Entity("GestionHotelSahaBeach.ReservationSalle", b =>
                {
                    b.Property<int>("idresersalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idresersalle"));

                    b.Property<DateTime?>("Date_arrivee")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_depart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_reser")
                        .HasColumnType("datetime2");

                    b.Property<int>("NombrePersonnes")
                        .HasColumnType("int");

                    b.Property<int?>("idclient")
                        .HasColumnType("int");

                    b.Property<int?>("idsalle")
                        .HasColumnType("int");

                    b.HasKey("idresersalle");

                    b.ToTable("ReservationSalle");
                });

            modelBuilder.Entity("GestionHotelSahaBeach.ReservationTab", b =>
                {
                    b.Property<int>("idresertab")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idresertab"));

                    b.Property<DateTime?>("Date_arrivee")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_depart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_reser")
                        .HasColumnType("datetime2");

                    b.Property<int>("NombrePersonnes")
                        .HasColumnType("int");

                    b.Property<int?>("idclient")
                        .HasColumnType("int");

                    b.Property<int?>("idtable")
                        .HasColumnType("int");

                    b.HasKey("idresertab");

                    b.ToTable("ReservationTab");
                });

            modelBuilder.Entity("GestionHotelSahaBeach.Salle", b =>
                {
                    b.Property<int>("idsalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idsalle"));

                    b.Property<string>("etat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("prix")
                        .HasColumnType("float");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idsalle");

                    b.ToTable("Salle");
                });

            modelBuilder.Entity("GestionHotelSahaBeach.Tabless", b =>
                {
                    b.Property<int>("idtable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idtable"));

                    b.Property<int>("NumTable")
                        .HasColumnType("int");

                    b.Property<string>("etat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("prix")
                        .HasColumnType("float");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idtable");

                    b.ToTable("Table");
                });

            modelBuilder.Entity("GestionHotelSahaBeach.Utilisateur", b =>
                {
                    b.Property<int>("iduser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("iduser"));

                    b.Property<string>("NomUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrenomUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("iduser");

                    b.ToTable("Utilisateur");
                });

            modelBuilder.Entity("GestionHotelSahaBeach.client", b =>
                {
                    b.Property<int>("idclient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idclient"));

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Types_pieces")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("date_arrivee")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("date_depart")
                        .HasColumnType("datetime2");

                    b.Property<string>("numPiece")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("télephone")
                        .HasColumnType("int");

                    b.HasKey("idclient");

                    b.ToTable("client");
                });

            modelBuilder.Entity("GestionHotelSahaBeach.Facture", b =>
                {
                    b.HasOne("GestionHotelSahaBeach.client", "client")
                        .WithMany()
                        .HasForeignKey("clientidclient");

                    b.Navigation("client");
                });
#pragma warning restore 612, 618
        }
    }
}
